Q1. Create two 3×3 matrices using the random function in Numpy and perform the following operations.

Product (prod)
Multiplication (multiply)
Dot Product (dot)

In [3]:
import numpy as np
arr1=np.random.randint(1,5,(3,3))
arr2=np.random.randint(1,6,(3,3))
print("Array1 : \n",arr1)
print("Array2 : \n",arr2)
print("Multiply : \n",np.multiply(arr1,arr2))
print("Product : \n",np.prod([arr1,arr2]))
print("Dot : \n",np.dot(arr1,arr2))

Array1 : 
 [[3 3 3]
 [1 3 4]
 [1 1 2]]
Array2 : 
 [[4 4 1]
 [2 2 5]
 [3 2 4]]
Multiply : 
 [[12 12  3]
 [ 2  6 20]
 [ 3  2  8]]
Product : 
 4976640
Dot : 
 [[27 24 30]
 [22 18 32]
 [12 10 14]]


Q2. Perform the following set operations using the Numpy functions.

Union
Intersection
Set difference
XOR

In [4]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
print("Union : ",np.union1d(arr1,arr2))

print("Intersection : ",np.intersect1d(arr1,arr2))

print("Set Difference : ",np.setdiff1d(arr1,arr2))

print("XOR : ",np.setxor1d(arr1,arr2))

Union :  [1 2 3 4 5 6]
Intersection :  [3 4]
Set Difference :  [1 2]
XOR :  [1 2 5 6]


Q3. Create a 1D array using Random function and perform the following operations.

Cumulative sum
Cumulative Product
Discrete difference (with n=3)
Find the unique elements from the array

In [5]:
import numpy as np
arr1=np.random.randint(10 ,size=10)
print(arr1)
print("Cumulative sum : ",np.cumsum(arr1))
print("Cumulative Product : ",np.cumprod(arr1))
print("Discrete difference (with n=3) : ",np.diff(arr1, n=3))
print("The unique elements from the array : ",np.unique(arr1))

[4 2 2 8 1 5 2 4 3 5]
Cumulative sum :  [ 4  6  8 16 17 22 24 28 31 36]
Cumulative Product :  [    4     8    16   128   128   640  1280  5120 15360 76800]
Discrete difference (with n=3) :  [  4 -19  24 -18  12  -8   6]
The unique elements from the array :  [1 2 3 4 5 8]


Q4. Create two 1D array and perform the Addition using zip(), add() and user defined function (frompyfunc())

In [6]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
z=[]
for i,j in zip(arr1,arr2):
    z.append(i+j)
print(z)

print(np.add(arr1,arr2))

def adds(x,y):
    return x+y
result=np.frompyfunc(adds,2,1)
print(result(arr1,arr2))

[4, 6, 8, 10]
[ 4  6  8 10]
[4 6 8 10]


Q5. Find the LCM (Least Common Multiple) and GCD (Greatest Common Divisor) of an array of elements using reduce().

In [7]:
import numpy as np
arr1=np.array([[[1,2,3,4]]])
arr2=np.array([5,25,15,10])
print("LCM : ",np.lcm.reduce(arr1))
print("GCD : ",np.gcd.reduce(arr2))

LCM :  [[1 2 3 4]]
GCD :  5
